server:
  port: 8080
  tomcat:
    accesslog:
      directory: /var/log/moa/base
      enabled: true
      pattern: common
      prefix: access_log
      suffix: .log
      rotate: true

management:
  security:
    enabled: false
  context-path: /manage